// example/example.tsx
interface Props {
    title: string;
    count?: number;
}
/**
* @description Press Your { Function Component } Description
* @param {Props} props
* @returns {void}
*/
function Component(props: Props) {
    return <div>{props.title}</div>;
}
/**
* @description Press Your { Function ArrowComponent } Description
* @param {Props} props
* @returns {JSX.Element}
*/
const ArrowComponent = (props: Props): JSX.Element => {
    return <div>{props.title}</div>;
};
export default Component;

// example/example.vue
<template>
  <div>{{ message }}</div>
</template>

<script>/**
* @description Press Your { Function greet } Description
* @param {any} name
* @returns {void}
*/
function greet(name) {
    return `Hello, ${name}`;
}
/**
* @description Press Your { Function farewell } Description
* @param {any} name
* @returns {void}
*/
const farewell = (name) => {
    return `Goodbye, ${name}`;
};
export default {
    name: 'ExampleComponent',
    setup() {
        return {
            greet,
            farewell
        };
    }
};
</script>

<style scoped>
div {
  color: blue;
}
</style>
